
version: 2.1

machine: &machine
  docker:
    - image: node:18.18.2

install_dependencies: &install_dependencies
  - run:
      name: Install pnpm package manager
      command: sudo npm i -g pnpm@7.11.0
  - restore_cache:
      keys:
      - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "pnpm-lock.yaml" }}
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-
  - run: pnpm install
  - save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "pnpm-lock.yaml" }}

jobs:
  build:
    <<: *machine
    steps:
      - checkout
      - <<: *install_dependencies
      - run: pnpm run lint
      - run: pnpm run test

  deploy:
    <<: *machine
    steps:
      - checkout
      - <<: *install_dependencies
      - run: pnpm run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npx semantic-release

workflows:
  build_deploy:
    jobs:
      - build:
          context: reaction-publish-semantic-release
      - deploy:
          context: reaction-publish-semantic-release
          requires:
            - build
          filters:
            branches:
              only: master
